fusion:
  brokers:
    - channel: NA
      hostUrl: 'tcp://fusion-activemq:61616'
      brokerId: fusionBroker
      jmsProvider: ACTIVEMQ
      queueManagerName: NA
      sendSessionCacheSize: 10
      userName: admin
spring:
  datasource:
    platform: mariadb
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb:failover://fusion-mariadb:3306/fusion?autoReconnect=true
    username: fusion
    password: fusion
    timeBetweenEvictionRunsMillis: 1000
    testWhileIdle: true
  liquibase:
    enabled: false
  hikari:
    connectionTimeout: 30000
    idleTimeout: 30000
    maxLifetime: 2000000
    maximumPoolSize: 20
    minimumIdle: 5
    poolName: SpringBootJPAHikariCP
  jpa:
    ddl-auto: ''
    show-sql: true
server:
  port: 9090
eraser:
  backOutDuration: 5000
  batchSize: 25
  duration: 60
  flushStatsPerCycle: true
  flushStatsPerOperation: false
  frequency: '0 0 4-13,18-23 * * ?'
  isEnabled: true
  shedlock:
    lockAtLeastFor: 1m
    lockAtMostFor: 10m
retentionDuration: 15
logsDirectory: '/tmp/fusion/auditor/'