fusion:
  brokers:
    - channel: NA
      hostUrl: 'tcp://127.0.0.1:61616'
      brokerId: fusionBroker
      jmsProvider: ACTIVEMQ
      queueManagerName: NA
      sendSessionCacheSize: 10
      userName: admin
      amqpRedeliveryPolicy:
         backOffMultiplier: 1.0
         maxDeliveries: 3
         queueNameRegex: "*"
         redeliveryDelay: 3000
         useExponentialBackOff: true
         maxDeliveryDelay: 3600000
         initialRedeliveryDelay: 0      
  usecases:
    - name: AuditEvent
      version: 1
      activeConfig: adapterConfig   
      configs:
        - name: adapterConfig
          adapters:
            - adapterType: inbound
              brokerId: fusionBroker
              queueName: FUSION.AUDIT.IN
              messageType: JSON
              readConcurrency: 5-10
              boBrokerId: fusionBroker
              boQueueName: FUSION.AUDIT.IN.BO 
            - adapterType: outbound
              trasnportType: JMS
              usecaseResult: FAILURE
              brokerId: fusionBroker
              queueName: FUSION.AUDIT.IN.ERROR                       
    
spring:
  datasource:
    platform: mariadb
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb:failover://localhost:3306/fusion?autoReconnect=true
    username: fusion
    password: fusion
    timeBetweenEvictionRunsMillis: 1000
    testWhileIdle: true
  liquibase:
    enabled: false
  hikari:
    connectionTimeout: 30000
    idleTimeout: 30000
    maxLifetime: 2000000
    maximumPoolSize: 20
    minimumIdle: 5
    poolName: SpringBootJPAHikariCP
  jpa:
    ddl-auto: ''
    show-sql: true
server:
  port: 9090
eraser:
  backOutDuration: 5000
  batchSize: 25
  duration: 60
  flushStatsPerCycle: true
  flushStatsPerOperation: false
  frequency: '0 27 10 * * ?'
  isEnabled: true
  shedlock:
    lockAtLeastFor: 1m
    lockAtMostFor: 10m
retentionDuration: 15